// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Authservice.Domain.Entites;
//step 1: create the user entity with the required properties and a collection of roles
public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public bool EmailConfirmed { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}